---
name: 'Get Environment'
author: <devops@futuresecure.ai>
description: 'Get the Environment for the workflow'
branding:
  icon: 'life-buoy'
  color: 'purple'

inputs:
  aws_account_name:
    description: aws account name
    required: true

outputs:
  aws_account_id:
    description: AWS Account Number of the Environment
    value: ${{ steps.get-env-terraform.outputs.aws_account_id }}

runs:
  using: "composite"
  steps:
    - name: Get Terraform Environment
      id: get-env-terraform
      shell: bash
      run: |
        # step: get-env-terraform

        case ${{ inputs.aws_account_name }} in
          dev)
            aws_account_id="803103365620"
            ;;

          esac

          echo "aws_account_id=$aws_account_id" | tee -a $GITHUB_OUTPUT
