---
name: 'Get Environment'
author: <devops@futuresecure.ai>
description: 'Get the Environment for the workflow'
branding:
  icon: 'life-buoy'
  color: 'purple'

inputs:
  environment:
    description: environment
    required: true

outputs:
  aws_account_id:
    description: AWS Account Number of the Environment
    value: ${{ steps.get-env-helmfile.outputs.aws_account_id }}

  aws_region:
    description: AWS Region of the Environment
    value: ${{ steps.get-env-helmfile.outputs.aws_region }}

runs:
  using: "composite"
  steps:
    - name: Get Helmfile Environment
      id: get-env-helmfile
      shell: bash
      run: |
        # step: get-env-helmfile

        case ${{ inputs.environment }} in
          sandbox)
            aws_account_id="783764599679"
            aws_region=ap-southeast-2
            ;;
          dev|rnd)
            aws_account_id="682033481043"
            aws_region=ap-southeast-2
            ;;
          sit|uat)
            aws_account_id="050752608492"
            aws_region=ap-southeast-2
            ;;
          prod)
            aws_account_id="340752804518"
            aws_region=ap-southeast-2
            ;;
          nam-prod)
            aws_account_id="942165496123"
            aws_region=us-east-2
            ;;
          nam-sit)
            aws_account_id="996960859408"
            aws_region=us-east-2
            ;;
          nam-dev)
            aws_account_id="409431482481"
            aws_region=us-east-2
            ;;
          us-dev)
            aws_account_id="705522375480"
            aws_region=us-east-2
            ;;
          us-devops)
            aws_account_id="273354621727"
            aws_region=us-east-2
            ;;
          sandbox-uat)
            aws_account_id="783764599679"
            aws_region=us-east-2
            ;;
          esac

          echo "aws_account_id=$aws_account_id" | tee -a $GITHUB_OUTPUT
          echo "aws_region=$aws_region" | tee -a $GITHUB_OUTPUT
