---
name: 'Get Environment'
author: <devops@futuresecure.ai>
description: 'Get the Environment for the workflow'
branding:
  icon: 'life-buoy'
  color: 'purple'

inputs:
  azure_subscription:
    description: azure subscription
    required: true

outputs:
  azure_client_id:
    description: Azure Application Client ID
    value: ${{ steps.get-env.outputs.azure_client_id }}

  azure_tenant_id:
    description: Azure Tenant ID
    value: ${{ steps.get-env.outputs.azure_tenant_id }}

  azure_subscription_id:
    description: Azure subscription ID
    value: ${{ steps.get-env.outputs.azure_subscription_id }}

runs:
  using: "composite"
  steps:
    - name: Get Terraform Environment
      id: get-env
      shell: bash
      run: |
        # step: get-env

        case ${{ inputs.azure_subscription }} in
          fsai-azure-us-internal-dev)
            azure_tenant_id="b6b2cf3f-9a4a-451d-8885-3fec2d0b2a94"
            azure_client_id="909b3019-f439-44e1-a8f8-a3036fd81c5d"
            azure_subscription_id="d4d12614-c859-4854-88fe-2e2a64ba592a"
            ;;
          esac

          echo "azure_tenant_id=$azure_tenant_id" | tee -a $GITHUB_OUTPUT
          echo "azure_client_id=$azure_client_id" | tee -a $GITHUB_OUTPUT
          echo "azure_subscription_id=$azure_subscription_id" | tee -a $GITHUB_OUTPUT
