name: 'Get Terraform Changed Directories'
description: 'Detects changed Terraform directories and creates a matrix for parallel execution'
inputs:
  filter:
    description: 'Path filter pattern for Terraform directories'
    required: true
    default: 'terraform/aws/overlay/**'
  base_ref:
    description: 'Base reference for comparison (default: main branch)'
    required: false
    default: 'origin/main'
outputs:
  matrix:
    description: 'JSON matrix of changed environments'
    value: ${{ steps.generate-matrix.outputs.matrix }}
  has_changes:
    description: 'Whether any Terraform files have changed'
    value: ${{ steps.generate-matrix.outputs.has_changes }}
  environments:
    description: 'List of changed environments'
    value: ${{ steps.generate-matrix.outputs.environments }}

runs:
  using: 'composite'
  steps:
    - name: ðŸ” Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v41
      with:
        files: ${{ inputs.filter }}
        dir_names: true
        dir_names_max_depth: 4

    - name: ðŸŽ¯ Generate matrix
      id: generate-matrix
      shell: bash
      run: |
        echo "ðŸ” Analyzing changed Terraform directories..."
        
        # Get unique environment directories that have changes
        changed_dirs=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -E "terraform/aws/overlay/[^/]+/eks" | sed 's|terraform/aws/overlay/||' | sed 's|/eks.*||' | sort -u)
        
        if [ -z "$changed_dirs" ]; then
          echo "No Terraform environment changes detected"
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "matrix={\"include\":[]}" >> $GITHUB_OUTPUT
          echo "environments=[]" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        echo "ðŸ“‚ Changed environments detected:"
        echo "$changed_dirs"
        
        # Build matrix JSON
        matrix_items=""
        environments_list=""
        
        for env in $changed_dirs; do
          if [ ! -z "$matrix_items" ]; then
            matrix_items="$matrix_items,"
            environments_list="$environments_list,"
          fi
          
          matrix_items="$matrix_items{\"environment\":\"$env\",\"terraform_dir\":\"terraform/aws/overlay/$env/eks\"}"
          environments_list="$environments_list\"$env\""
          
          echo "  - $env (terraform/aws/overlay/$env/eks)"
        done
        
        matrix_json="{\"include\":[$matrix_items]}"
        environments_json="[$environments_list]"
        
        echo "ðŸŽ¯ Generated matrix: $matrix_json"
        echo "ðŸ“‹ Environments list: $environments_json"
        
        echo "has_changes=true" >> $GITHUB_OUTPUT
        echo "matrix=$matrix_json" >> $GITHUB_OUTPUT
        echo "environments=$environments_json" >> $GITHUB_OUTPUT

    - name: ðŸ“Š Matrix Summary
      shell: bash
      run: |
        echo "## ðŸ“Š Terraform Changes Detection" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.generate-matrix.outputs.has_changes }}" == "true" ]; then
          echo "### âœ… Changed Environments:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          environments=$(echo '${{ steps.generate-matrix.outputs.environments }}' | jq -r '.[]')
          for env in $environments; do
            echo "- ðŸŽ¯ **$env** (\`terraform/aws/overlay/$env/eks\`)" >> $GITHUB_STEP_SUMMARY
          done
        else
          echo "### â„¹ï¸ No Terraform environment changes detected" >> $GITHUB_STEP_SUMMARY
          echo "No environments will be processed in this workflow run." >> $GITHUB_STEP_SUMMARY
        fi